# Generated by Django 4.2.16 on 2024-11-25 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sound_local',
            field=models.FileField(blank=True, null=True, upload_to='animal_sounds/'),
        ),
    ]
