# Generated by Django 4.2.16 on 2024-11-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
    ]
