# Generated by Django 4.2.16 on 2024-11-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='habitat',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='species',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
