# Generated by Django 4.2.16 on 2024-11-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0002_blogpost_likes_blogpost_read_comment_approved_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='read',
            new_name='approve',
        ),
    ]
