# Generated by Django 4.2.16 on 2024-11-22 14:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0002_alter_blogpost_featured_image_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sound_local',
            field=models.FileField(blank=True, null=True, upload_to='animal_sounds/'),
        ),
    ]
