# Generated by Django 4.2.16 on 2024-10-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_on', 'author']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
