# Generated by Django 4.2.16 on 2024-11-27 13:44

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echoes', '0002_rename_content_blogpost_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['date', 'author']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_on',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('featured_image_local', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='echoes.blogpost')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='echoes.tag'),
        ),
    ]
