# Generated by Django 4.2.16 on 2024-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0003_tag_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='diet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
