# Generated by Django 4.2.16 on 2024-11-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0004_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='sound_cloudinary',
        ),
    ]
