# Generated by Django 4.2.16 on 2024-11-09 13:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0004_remove_blogpost_image_blogpost_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='sound',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_local',
            field=models.FileField(blank=True, null=True, upload_to='static/animal_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sound_cloudinary',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sound'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sound_local',
            field=models.FileField(blank=True, default='no sound', null=True, upload_to='static/sound/animals_sounds/'),
        ),
    ]
