# Generated by Django 4.2.16 on 2024-11-22 16:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0005_remove_blogpost_sound_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sound_cloudinary',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sound'),
        ),
    ]
