# Generated by Django 4.2.16 on 2024-11-27 17:40

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0007_blogpost_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostimage',
            old_name='featured_image',
            new_name='image_gallery',
        ),
        migrations.RemoveField(
            model_name='blogpostimage',
            name='featured_image_local',
        ),
        migrations.RemoveField(
            model_name='funfactslider',
            name='animal_name',
        ),
        migrations.RemoveField(
            model_name='funfactslider',
            name='image',
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='image_gallery_local',
            field=models.ImageField(blank=True, null=True, upload_to='animal_gallery_images/'),
        ),
        migrations.AddField(
            model_name='funfactslider',
            name='blog_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='echoes.blogpost'),
        ),
        migrations.AddField(
            model_name='funfactslider',
            name='slider_image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='funfactslider',
            name='slider_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='species',
            field=models.CharField(default=None, max_length=85),
        ),
    ]
