# Generated by Django 4.2.16 on 2024-11-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0008_rename_featured_image_blogpostimage_image_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='fun_facts',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_facts', to='echoes.animalfact', verbose_name='Fun Facts'),
        ),
    ]
