# Generated by Django 4.2.16 on 2024-11-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0008_blogpost_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
