# Generated by Django 4.2.16 on 2024-11-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0012_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
