# Generated by Django 4.2.16 on 2024-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0013_blogpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='unauthenticated_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
